from sqlalchemy.orm import Session
from sqlalchemy import func
from datetime import datetime, timedelta
from typing import Optional, List, Dict, Any

from src.models.receptionist import Receptionist, ReceptionistModel, ReceptionistUpdate
from src.models.patients import Patient, QuickRegistration
from src.models.admin import AdminModel # To check for Doctors
# Assuming you've moved Consultation and Notification to SQLAlchemy as well
# from src.models.patients import Consultation, Notification, NotificationType 

from src.services.queue_manager import QueueManager

class ReceptionistService:

    # ----------------------
    # Dashboard Stats (DB Version)
    # ----------------------
    @staticmethod
    def get_dashboard_stats(db: Session) -> Dict:
        """Get real-time dashboard statistics from the database"""
        try:
            today_start = datetime.utcnow().replace(hour=0, minute=0, second=0, microsecond=0)
            
            # Count patients registered today
            registered_today = db.query(Patient).filter(Patient.created_at >= today_start).count()
            
            # Get Queue Manager stats (waiting/in-progress)
            queue_stats = QueueManager.get_queue_stats()
            
            # Fetch recent registrations from the Patient table
            recent_patients = db.query(Patient).order_by(Patient.created_at.desc()).limit(5).all()
            
            recent_list = [{
                "name": p.name,
                "phone": p.phone,
                "time": p.created_at.isoformat()
            } for p in recent_patients]

            return {
                "success": True,
                "total_in_queue": queue_stats.get("waiting", 0),
                "registered_today": registered_today,
                "in_progress": queue_stats.get("in_progress", 0),
                "recent_registrations": recent_list,
                "timestamp": datetime.now().isoformat()
            }
        except Exception as e:
            return {"success": False, "error": str(e)}

    # ----------------------
    # Quick Patient Registration
    # ----------------------
    @staticmethod
    def quick_register_patient(db: Session, registration: QuickRegistration, receptionist_id: int) -> Dict:
        """Quickly register/find a patient and push them into the QueueManager"""
        try:
            # 1. Check if patient exists by phone
            patient = db.query(Patient).filter(Patient.phone == registration.phone).first()
            is_new = False

            if not patient:
                patient = Patient(
                    name=registration.patient_name,
                    phone=registration.phone,
                    age=registration.age,
                    gender=registration.gender,
                    created_at=datetime.utcnow()
                )
                db.add(patient)
                db.commit()
                db.refresh(patient)
                is_new = True

            # 2. Integrate with QueueManager
            # We pass the patient.id generated by SQLAlchemy
            queue_result = QueueManager.add_to_queue(
                patient_id=patient.id,
                department=registration.department or "General",
                priority=registration.priority or 3,
                condition=registration.condition or "General Checkup",
                doctor_id=registration.doctor_id
            )

            if queue_result.get("success"):
                return {
                    "success": True,
                    "patient_id": patient.id,
                    "patient_name": patient.name,
                    "queue_number": queue_result.get("queue_number"),
                    "is_new_patient": is_new,
                    "message": "Patient successfully queued"
                }
            
            return {"success": False, "error": "Queue assignment failed"}

        except Exception as e:
            db.rollback()
            return {"success": False, "error": str(e)}

    # ----------------------
    # Receptionist Management
    # ----------------------
    @staticmethod
    def get_all_receptionists(db: Session) -> Dict:
        """Fetch all receptionists from DB"""
        recs = db.query(Receptionist).all()
        return {
            "success": True,
            "receptionists": [
                {
                    "id": r.id,
                    "employee_id": r.employee_id,
                    "name": r.name,
                    "status": r.status,
                    "last_login": r.last_login.isoformat() if r.last_login else None
                } for r in recs
            ]
        }

    @staticmethod
    def update_receptionist(db: Session, r_id: int, data: ReceptionistUpdate) -> Dict:
        """Update a receptionist record"""
        rec = db.query(Receptionist).filter(Receptionist.id == r_id).first()
        if not rec:
            return {"success": False, "error": "Receptionist not found"}
        
        # Update only fields provided in the schema
        update_data = data.dict(exclude_unset=True)
        for key, value in update_data.items():
            setattr(rec, key, value)
        
        db.commit()
        return {"success": True, "message": "Record updated"}

    @staticmethod
    def delete_receptionist(db: Session, r_id: int) -> Dict:
        """Soft delete (deactivate) a receptionist"""
        rec = db.query(Receptionist).filter(Receptionist.id == r_id).first()
        if rec:
            rec.status = "inactive"
            db.commit()
            return {"success": True, "message": "Receptionist deactivated"}
        return {"success": False, "error": "Not found"}

    # ----------------------
    # Search Patients
    # ----------------------
    @staticmethod
    def search_patients(db: Session, query: str) -> Dict:
        """Search database for patients by name or phone number"""
        if not query or len(query) < 3:
            return {"success": False, "error": "Search query too short"}
            
        patients = db.query(Patient).filter(
            (Patient.name.ilike(f"%{query}%")) | 
            (Patient.phone.ilike(f"%{query}%"))
        ).all()

        return {
            "success": True,
            "results": [{"id": p.id, "name": p.name, "phone": p.phone} for p in patients]
        }